sudo: required
language: node_js

node_js:
  - "0.12"
    
before_script:
 # - npm link
 # - mkdir -p shippable/codecoverage

after_success:
  - echo $TOTO
  - git remote -v
  - git config --global user.email "pg6499@g.rit.edu"
  - git config --global user.name "pg6499"
  - git checkout master
  - npm version patch
  - git commit -am "[skip ci] bump version"
  - git log --oneline
  - git remote set-url origin git@github.com:pg6499/Travis.git
  - git push origin master
  
script:
  - chmod u+x hello.js
  - node hello.js
#  - npm run coverage
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - mocha test -R mocha-lcov-reporter  && 
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate
